### ISSUE TITLE
1nic custom onboard example references aws

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-gcp-bigip-module#5] opened 2021-11-05 22:42 UTC
This example uses aws for metadata. Needs to be updated for GCP stuff.

https://github.com/F5Networks/terraform-gcp-bigip-module/blob/main/examples/bigip_gcp_1nic_deploy_custom_runtime_init/custom_onboard_big.tmpl

example...
```
if ${aws_secretmanager_auth}
then
   cat << 'EOF' >> /config/cloud/runtime-init-conf.yaml
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      environment: aws
      type: SecretsManager
      version: AWSCURRENT
      secretId: ${bigip_password}
EOF
```

**Comment by trinaths** [comment] 2021-11-23 09:40
duplicate of https://github.com/F5Networks/terraform-gcp-bigip-module/issues/4 

closing this issue.

**Closed by trinaths** 2021-11-23 09:40 UTC
